### ISSUE TITLE
[BUG] `@commitlint/config-conventional` failing to load

### ISSUE THREAD

**Issue by akrawitz** [vivaxy/vscode-conventional-commits#401]
### Describe the bug

Starting with version `1.28.1`, in my Windows 11 environment, the extension fails to load `node_modules/@commitlint/config-conventional/lib/index.js`.

(Note that it works fine in version `1.27.0`, and as noted in #383, with version `1.28.0`, the extension totally fails to load.)

### To reproduce

My `.commitlintrc.json` starts with:

```json
{
  "extends": [
    "@commitlint/config-conventional"
  ],
```

If I remove this `extends` from my configuration, then the problem goes away, but of course I don't get the "Conventional Commits" configuration.

### Expected behavior

I expect `@commitlint/config-conventional` to be successfully loaded as part of my configuration.

### Screenshots

NA

### Application logs

I've put the full log below. I believe the critical line is:
`[warning] commitlint: Cannot find module 'file:///c:/Users/akrawitz.UVIC/OneDrive%20-%20University%20of%20Victoria/Research%20-%20Victoria/Misc/decidables/node_modules/@commitlint/config-conventional/lib/index.js'`

Note that when I look in `node_modules` the package (`@commitlint/config-conventional`) and file (`/lib/index.js`) are there as they should be. So my best guess is that the patch in #384 may not be handling the Windows file paths correctly? Perhaps the spaces aren't being escaped properly?

```
[info] Extension Activated
[info] vscode.env.language: en
[info] Conventional commits started.
[info] VSCode version: 1.121.0
[info] Git version: 10.0.0
[info] VSCode Conventional Commits version: 1.29.0
[info] conventionalCommits.autoCommit: false
[info] conventionalCommits.storeScopesGlobally: false
[info] conventionalCommits.storeTagsGlobally: undefined
[info] conventionalCommits.silentAutoCommit: false
[info] conventionalCommits.emojiFormat: code
[info] conventionalCommits.gitmoji: false
[info] conventionalCommits.lineBreak: \n
[info] conventionalCommits.promptBody: true
[info] conventionalCommits.promptCI: false
[info] conventionalCommits.promptFooter: true
[info] conventionalCommits.promptScopes: true
[info] conventionalCommits.scopes: 
[info] conventionalCommits.promptTag: undefined
[info] conventionalCommits.tags: undefined
[info] conventionalCommits.showEditor: false
[info] conventionalCommits.showNewVersionNotes: false
[info] conventionalCommits.editor.keepAfterSave: false
[info] git.enableSmartCommit: false
[info] git.smartCommitChanges: all
[info] git.postCommitCommand: none
[info] _arg: c:\Users\akrawitz.UVIC\OneDrive - University of Victoria\Research - Victoria\Misc\decidables
[info] git.repositories: c:\Users\akrawitz.UVIC\OneDrive - University of Victoria\Research - Victoria\Misc\decidables
[info] workspaceFolders: c:\Users\akrawitz.UVIC\OneDrive - University of Victoria\Research - Victoria\Misc\decidables
[warning] commitlint: The cwd is c:\Users\akrawitz.UVIC\OneDrive - University of Victoria\Research - Victoria\Misc\decidables
[warning] commitlint: Cannot find module 'file:///c:/Users/akrawitz.UVIC/OneDrive%20-%20University%20of%20Victoria/Research%20-%20Victoria/Misc/decidables/node_modules/@commitlint/config-conventional/lib/index.js'
Require stack:
- c:\Users\akrawitz.UVIC\.vscode\extensions\vivaxy.vscode-conventional-commits-1.29.0\dist\extension.js
- c:\Program Files\Microsoft VS Code\f6cfa2ea24\resources\app\out\vs\workbench\api\node\extensionHostProcess.js
[info] commitlintRuleConfigs:
{}
```

**Comment by vivaxy** [comment]
Thanks @akrawitz for the feedback.
Commit ce084c280e6c98b51d53556d164821b6e861eec6 should do the fix.
Please try version 1.31.0.

**Comment by akrawitz** [comment]
Thank you @vivaxy, version 1.31.0 is working for me!
👍
